#!/usr/bin/env bash
# Produce every Windows distributable from a configured build directory:
#
#   dist tree   jcat-tool-<version>-x86_64/
#   zip         jcat-tool-<version>-x86_64.zip
#   installer   jcat-tool-<version>-x86_64-setup.exe
#
# Usage:
#   contrib/win32/mkdist.sh [build-dir] [toolchain-prefix]
#
# Run from anywhere; paths are resolved relative to the repository.

set -euo pipefail

BUILD_DIR="${1:-build}"
PREFIX="${2:-${MINGW_PREFIX:-}}"

SRC_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$SRC_ROOT"

if [ ! -f "$BUILD_DIR/config.h" ]; then
	echo "error: '$BUILD_DIR' is not a configured meson build directory" >&2
	echo "       run: meson setup $BUILD_DIR -Dgpg=false -Dman=false -Dgtkdoc=false" >&2
	exit 1
fi

# config.h is generated by meson from the project version, so it always agrees
# with the binaries in this build directory -- unlike anything parsed out of
# meson.build, which may have moved on
VERSION=$(sed -n 's/^#define PACKAGE_VERSION "\(.*\)"$/\1/p' "$BUILD_DIR/config.h")
if [ -z "$VERSION" ]; then
	echo "error: no PACKAGE_VERSION in $BUILD_DIR/config.h" >&2
	exit 1
fi

NAME="jcat-tool-${VERSION}-x86_64"
echo "==> building $NAME"

# --- dist tree ----------------------------------------------------------------
# name the bundle after the release so the zip has a versioned top-level
# directory rather than spilling bin/ and lib/ into the user's current folder
contrib/win32/bundle.sh "$BUILD_DIR" "$NAME" ${PREFIX:+"$PREFIX"}

# --- zip ----------------------------------------------------------------------
rm -f "$NAME.zip"
if command -v bsdtar >/dev/null 2>&1; then
	# bsdtar ships with libarchive, which pacman depends on, so it is always
	# present under MSYS2 -- unlike the optional 'zip' package
	bsdtar -a -cf "$NAME.zip" "$NAME"
elif command -v zip >/dev/null 2>&1; then
	zip -qr "$NAME.zip" "$NAME"
else
	echo "error: neither bsdtar nor zip found; pacman -S zip" >&2
	exit 1
fi
echo "==> wrote $NAME.zip"

# --- installer ----------------------------------------------------------------
if command -v makensis >/dev/null 2>&1; then
	# NSIS resolves SRCDIR and OutFile relative to the .nsi file, hence ../../
	makensis -V2 -DVERSION="$VERSION" -DSRCDIR="../../$NAME" \
		contrib/win32/jcat-tool.nsi
	# keep the artefacts together rather than leaving one under contrib/
	mv -f "contrib/win32/${NAME}-setup.exe" .
	echo "==> wrote ${NAME}-setup.exe"
else
	echo "note: makensis not found, skipping the installer"
	echo "      pacman -S ${MINGW_PACKAGE_PREFIX:-mingw-w64-ucrt-x86_64}-nsis"
fi

echo
echo "artefacts:"
ls -la "$NAME.zip" "${NAME}-setup.exe" 2>/dev/null | awk '{printf "  %-48s %s bytes\n", $NF, $5}'
echo
echo "Verify the bundle from cmd.exe with a minimal PATH, not from this shell:"
echo "  set PATH=%SystemRoot%\\system32;%SystemRoot%"
echo "  $NAME\\bin\\jcat-tool.exe --version"
